// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package bitswap_message_pb

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_BlockPresenceType int32

const (
	Message_Have     Message_BlockPresenceType = 0
	Message_DontHave Message_BlockPresenceType = 1
)

var Message_BlockPresenceType_name = map[int32]string{
	0: "Have",
	1: "DontHave",
}

var Message_BlockPresenceType_value = map[string]int32{
	"Have":     0,
	"DontHave": 1,
}

func (x Message_BlockPresenceType) String() string {
	return proto.EnumName(Message_BlockPresenceType_name, int32(x))
}

func (Message_BlockPresenceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

type Message_Wantlist_WantType int32

const (
	Message_Wantlist_Block Message_Wantlist_WantType = 0
	Message_Wantlist_Have  Message_Wantlist_WantType = 1
)

var Message_Wantlist_WantType_name = map[int32]string{
	0: "Block",
	1: "Have",
}

var Message_Wantlist_WantType_value = map[string]int32{
	"Block": 0,
	"Have":  1,
}

func (x Message_Wantlist_WantType) String() string {
	return proto.EnumName(Message_Wantlist_WantType_name, int32(x))
}

func (Message_Wantlist_WantType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0, 0}
}

type Message struct {
	Wantlist             *Message_Wantlist        `protobuf:"bytes,1,opt,name=wantlist,proto3" json:"wantlist,omitempty"`
	Blocks               [][]byte                 `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	Payload              []*Message_Block         `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty"`
	BlockPresences       []*Message_BlockPresence `protobuf:"bytes,4,rep,name=blockPresences,proto3" json:"blockPresences,omitempty"`
	PendingBytes         int32                    `protobuf:"varint,5,opt,name=pendingBytes,proto3" json:"pendingBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetWantlist() *Message_Wantlist {
	if m != nil {
		return m.Wantlist
	}
	return nil
}

func (m *Message) GetBlocks() [][]byte {
	if m != nil {
		return m.Blocks
	}
	return nil
}

func (m *Message) GetPayload() []*Message_Block {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *Message) GetBlockPresences() []*Message_BlockPresence {
	if m != nil {
		return m.BlockPresences
	}
	return nil
}

func (m *Message) GetPendingBytes() int32 {
	if m != nil {
		return m.PendingBytes
	}
	return 0
}

type Message_Wantlist struct {
	Entries              []*Message_Wantlist_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Full                 bool                      `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Message_Wantlist) Reset()         { *m = Message_Wantlist{} }
func (m *Message_Wantlist) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist) ProtoMessage()    {}
func (*Message_Wantlist) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0}
}

func (m *Message_Wantlist) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist.Unmarshal(m, b)
}
func (m *Message_Wantlist) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist.Marshal(b, m, deterministic)
}
func (m *Message_Wantlist) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist.Merge(m, src)
}
func (m *Message_Wantlist) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist.Size(m)
}
func (m *Message_Wantlist) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist proto.InternalMessageInfo

func (m *Message_Wantlist) GetEntries() []*Message_Wantlist_Entry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *Message_Wantlist) GetFull() bool {
	if m != nil {
		return m.Full
	}
	return false
}

type Message_Wantlist_Entry struct {
	Block                []byte                    `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Priority             int32                     `protobuf:"varint,2,opt,name=priority,proto3" json:"priority,omitempty"`
	Cancel               bool                      `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel,omitempty"`
	WantType             Message_Wantlist_WantType `protobuf:"varint,4,opt,name=wantType,proto3,enum=bitswap.message.pb.Message_Wantlist_WantType" json:"wantType,omitempty"`
	SendDontHave         bool                      `protobuf:"varint,5,opt,name=sendDontHave,proto3" json:"sendDontHave,omitempty"`
	Token                string                    `protobuf:"bytes,6,opt,name=Token,proto3" json:"Token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Message_Wantlist_Entry) Reset()         { *m = Message_Wantlist_Entry{} }
func (m *Message_Wantlist_Entry) String() string { return proto.CompactTextString(m) }
func (*Message_Wantlist_Entry) ProtoMessage()    {}
func (*Message_Wantlist_Entry) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 0, 0}
}

func (m *Message_Wantlist_Entry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Wantlist_Entry.Unmarshal(m, b)
}
func (m *Message_Wantlist_Entry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Wantlist_Entry.Marshal(b, m, deterministic)
}
func (m *Message_Wantlist_Entry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Wantlist_Entry.Merge(m, src)
}
func (m *Message_Wantlist_Entry) XXX_Size() int {
	return xxx_messageInfo_Message_Wantlist_Entry.Size(m)
}
func (m *Message_Wantlist_Entry) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Wantlist_Entry.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Wantlist_Entry proto.InternalMessageInfo

func (m *Message_Wantlist_Entry) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *Message_Wantlist_Entry) GetPriority() int32 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func (m *Message_Wantlist_Entry) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

func (m *Message_Wantlist_Entry) GetWantType() Message_Wantlist_WantType {
	if m != nil {
		return m.WantType
	}
	return Message_Wantlist_Block
}

func (m *Message_Wantlist_Entry) GetSendDontHave() bool {
	if m != nil {
		return m.SendDontHave
	}
	return false
}

func (m *Message_Wantlist_Entry) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Message_Block struct {
	Prefix               []byte   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message_Block) Reset()         { *m = Message_Block{} }
func (m *Message_Block) String() string { return proto.CompactTextString(m) }
func (*Message_Block) ProtoMessage()    {}
func (*Message_Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 1}
}

func (m *Message_Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_Block.Unmarshal(m, b)
}
func (m *Message_Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_Block.Marshal(b, m, deterministic)
}
func (m *Message_Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_Block.Merge(m, src)
}
func (m *Message_Block) XXX_Size() int {
	return xxx_messageInfo_Message_Block.Size(m)
}
func (m *Message_Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Message_Block proto.InternalMessageInfo

func (m *Message_Block) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

func (m *Message_Block) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message_BlockPresence struct {
	Cid                  []byte                    `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Type                 Message_BlockPresenceType `protobuf:"varint,2,opt,name=type,proto3,enum=bitswap.message.pb.Message_BlockPresenceType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *Message_BlockPresence) Reset()         { *m = Message_BlockPresence{} }
func (m *Message_BlockPresence) String() string { return proto.CompactTextString(m) }
func (*Message_BlockPresence) ProtoMessage()    {}
func (*Message_BlockPresence) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0, 2}
}

func (m *Message_BlockPresence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message_BlockPresence.Unmarshal(m, b)
}
func (m *Message_BlockPresence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message_BlockPresence.Marshal(b, m, deterministic)
}
func (m *Message_BlockPresence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message_BlockPresence.Merge(m, src)
}
func (m *Message_BlockPresence) XXX_Size() int {
	return xxx_messageInfo_Message_BlockPresence.Size(m)
}
func (m *Message_BlockPresence) XXX_DiscardUnknown() {
	xxx_messageInfo_Message_BlockPresence.DiscardUnknown(m)
}

var xxx_messageInfo_Message_BlockPresence proto.InternalMessageInfo

func (m *Message_BlockPresence) GetCid() []byte {
	if m != nil {
		return m.Cid
	}
	return nil
}

func (m *Message_BlockPresence) GetType() Message_BlockPresenceType {
	if m != nil {
		return m.Type
	}
	return Message_Have
}

func init() {
	proto.RegisterEnum("bitswap.message.pb.Message_BlockPresenceType", Message_BlockPresenceType_name, Message_BlockPresenceType_value)
	proto.RegisterEnum("bitswap.message.pb.Message_Wantlist_WantType", Message_Wantlist_WantType_name, Message_Wantlist_WantType_value)
	proto.RegisterType((*Message)(nil), "bitswap.message.pb.Message")
	proto.RegisterType((*Message_Wantlist)(nil), "bitswap.message.pb.Message.Wantlist")
	proto.RegisterType((*Message_Wantlist_Entry)(nil), "bitswap.message.pb.Message.Wantlist.Entry")
	proto.RegisterType((*Message_Block)(nil), "bitswap.message.pb.Message.Block")
	proto.RegisterType((*Message_BlockPresence)(nil), "bitswap.message.pb.Message.BlockPresence")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xe7, 0x26, 0x69, 0xb3, 0xd3, 0x6e, 0x2a, 0x16, 0x42, 0x56, 0x24, 0xd4, 0xac, 0xe2,
	0x22, 0x80, 0x96, 0x49, 0xdd, 0x13, 0xac, 0xfc, 0x11, 0x20, 0x21, 0x21, 0x6b, 0x52, 0xaf, 0xf3,
	0xc7, 0x2d, 0xd6, 0x32, 0x3b, 0xc4, 0x2e, 0xa3, 0x6f, 0xc8, 0x33, 0x70, 0xb1, 0x1b, 0x9e, 0x00,
	0x9e, 0x00, 0xe5, 0xc4, 0xad, 0x54, 0x86, 0xd8, 0xee, 0xfc, 0x1d, 0x9f, 0xef, 0x17, 0x9f, 0xef,
	0x28, 0x70, 0x74, 0x2d, 0x8c, 0xc9, 0x56, 0x22, 0xad, 0x1b, 0x6d, 0x35, 0xa5, 0xb9, 0xb4, 0xe6,
	0x26, 0xab, 0xd3, 0x5d, 0x39, 0x8f, 0x4e, 0x57, 0xd2, 0x7e, 0x5e, 0xe7, 0x69, 0xa1, 0xaf, 0xcf,
	0x56, 0x7a, 0xa5, 0xcf, 0xb0, 0x35, 0x5f, 0x2f, 0x51, 0xa1, 0xc0, 0x53, 0x87, 0x98, 0xfe, 0xee,
	0xc3, 0xe0, 0x63, 0xe7, 0xa6, 0x6f, 0x21, 0xbc, 0xc9, 0x94, 0xad, 0xa4, 0xb1, 0x8c, 0xc4, 0x24,
	0x19, 0xce, 0x9e, 0xa5, 0x77, 0xbf, 0x90, 0xba, 0xf6, 0x74, 0xe1, 0x7a, 0xe7, 0xfe, 0xf7, 0xdb,
	0xc9, 0x01, 0xdf, 0x79, 0xe9, 0x13, 0xe8, 0xe7, 0x95, 0x2e, 0xae, 0x0c, 0xeb, 0xc5, 0x5e, 0x32,
	0xe2, 0x4e, 0xd1, 0x0b, 0x18, 0xd4, 0xd9, 0xa6, 0xd2, 0x59, 0xc9, 0xbc, 0xd8, 0x4b, 0x86, 0xb3,
	0x93, 0xff, 0xe1, 0xe7, 0xad, 0xc9, 0xb1, 0xb7, 0x3e, 0xba, 0x80, 0x63, 0x84, 0x7d, 0x6a, 0x84,
	0x11, 0xaa, 0x10, 0x86, 0xf9, 0x48, 0x7a, 0x7e, 0x2f, 0x69, 0xeb, 0x70, 0xc4, 0xbf, 0x30, 0x74,
	0x0a, 0xa3, 0x5a, 0xa8, 0x52, 0xaa, 0xd5, 0x7c, 0x63, 0x85, 0x61, 0x41, 0x4c, 0x92, 0x80, 0xef,
	0xd5, 0xa2, 0x5f, 0x3d, 0x08, 0xb7, 0x43, 0xd3, 0x0f, 0x30, 0x10, 0xca, 0x36, 0x52, 0x18, 0x46,
	0xf0, 0x09, 0x2f, 0x1e, 0x92, 0x55, 0xfa, 0x46, 0xd9, 0x66, 0xb3, 0x9d, 0xca, 0x01, 0x28, 0x05,
	0x7f, 0xb9, 0xae, 0x2a, 0xd6, 0x8b, 0x49, 0x12, 0x72, 0x3c, 0x47, 0x3f, 0x09, 0x04, 0xd8, 0x4c,
	0x4f, 0x20, 0xc0, 0xc7, 0xe2, 0x4e, 0x46, 0xf3, 0x61, 0xeb, 0xfd, 0x71, 0x3b, 0xf1, 0x5e, 0xc9,
	0x92, 0x77, 0x37, 0x34, 0x82, 0xb0, 0x6e, 0xa4, 0x6e, 0xa4, 0xdd, 0x20, 0x24, 0xe0, 0x3b, 0xdd,
	0x6e, 0xa3, 0xc8, 0x54, 0x21, 0x2a, 0xe6, 0x21, 0xde, 0x29, 0xfa, 0xbe, 0xdb, 0xf6, 0xe5, 0xa6,
	0x16, 0xcc, 0x8f, 0x49, 0x72, 0x3c, 0x3b, 0x7d, 0xd0, 0x04, 0x0b, 0x67, 0xe2, 0x3b, 0x7b, 0x1b,
	0x9e, 0x11, 0xaa, 0x7c, 0xad, 0x95, 0x7d, 0x97, 0x7d, 0x15, 0x18, 0x5e, 0xc8, 0xf7, 0x6a, 0xf4,
	0x31, 0x04, 0x97, 0xfa, 0x4a, 0x28, 0xd6, 0x8f, 0x49, 0x72, 0xc8, 0x3b, 0x31, 0x9d, 0x74, 0x89,
	0x22, 0xe5, 0x10, 0x02, 0xdc, 0xd4, 0xf8, 0x80, 0x86, 0xe0, 0xb7, 0xa6, 0x31, 0x89, 0xce, 0x5d,
	0xb1, 0x1d, 0xa3, 0x6e, 0xc4, 0x52, 0x7e, 0xeb, 0x62, 0xe0, 0x4e, 0xb5, 0xd9, 0x95, 0x99, 0xcd,
	0x70, 0xec, 0x11, 0xc7, 0x73, 0xf4, 0x05, 0x8e, 0xf6, 0x76, 0x4e, 0x9f, 0x82, 0x57, 0xc8, 0xf2,
	0x5f, 0x01, 0xb6, 0x75, 0x7a, 0x01, 0xbe, 0x6d, 0x63, 0xe8, 0xdd, 0x1f, 0xc3, 0x1e, 0x17, 0x63,
	0x40, 0xeb, 0xf4, 0x25, 0x3c, 0xba, 0x73, 0xb5, 0x1b, 0xe3, 0x80, 0x8e, 0x20, 0xdc, 0x26, 0x31,
	0x26, 0x79, 0x1f, 0xff, 0xbd, 0xf3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x49, 0xe7, 0xfa,
	0xcf, 0x03, 0x00, 0x00,
}
